name: 'Givve Automatic Deployment'
description: 'Provide a description here'
author: 'PL Gutscheinsysteme GmbH'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  semaphoreAPI:
    description: 'Semaphore API to be queried'
    required: true
  semaphoreAPIKey:
    description: 'Semaphore API key for authorization'
    required: true
  pull_request:
    description: 'Pull Request that triggered the action'
    required: true
  component:
    description: 'Component to be deployed'
    required: true

# Define your outputs here.
outputs:
  deployment_permitted:
    description: 'If true, automatic deployment can continue'

runs:
  using: node20
  main: dist/index.js
